spring:
  application:
    name: zuul-api-gateway-server
  zipkin:
    base-url: http://localhost:9411/
server:
  port: 8765
eureka:
  client:
    service-url:
      default-zome: http://localhost:8761/eureka